// <auto-generated />
using BlueWolf.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlueWolf.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.7.23375.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlueWolf.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Displayorder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Displayorder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Displayorder = 2,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 3,
                            Displayorder = 3,
                            Name = "History"
                        });
                });

            modelBuilder.Entity("BlueWolf.Models.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Framing")
                        .HasColumnType("bit");

                    b.Property<int>("ImageRating")
                        .HasColumnType("int");

                    b.Property<int>("ImageSize")
                        .HasColumnType("int");

                    b.Property<bool>("Matting")
                        .HasColumnType("bit");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The Native American Chief Recaling his life",
                            Framing = false,
                            ImageRating = 1,
                            ImageSize = 1,
                            Matting = false,
                            Price = 20.0,
                            Title = "Looking Into The Past",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Sunset of Chips of Glass",
                            Framing = false,
                            ImageRating = 1,
                            ImageSize = 1,
                            Matting = false,
                            Price = 20.0,
                            Title = "Mosaic Sunset",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Illustration of an Eggplant",
                            Framing = false,
                            ImageRating = 1,
                            ImageSize = 1,
                            Matting = false,
                            Price = 20.0,
                            Title = "Eggplant",
                            Type = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
